# Generated by Django 4.2.5 on 2023-09-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='city',
        ),
        migrations.RemoveField(
            model_name='member',
            name='country',
        ),
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='state',
        ),
        migrations.RemoveField(
            model_name='member',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
